FROM centos:7.7.1908
# RUN useradd ${USER_NAME}
RUN yum update -y
RUN yum -y install http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
RUN yum -y install --enablerepo=remi,remi-php72 php php-mbstring php-xml php-xmlrpc php-gd php-pdo php-pecl-mcrypt php-mysqlnd php-pecl-mysql
RUN rm -rf /etc/php.ini
RUN ln -s /home/${USER_NAME}/${DOMAIN_NAME}/xserver_php/php.ini /etc/php.ini
WORKDIR /home/${USER_NAME}/
# RUN systemctl restart httpd
# RUN su ${USER_NAME}